# Generated by Django 2.2.1 on 2019-05-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the article.', max_length=100)),
                ('body', models.TextField(blank=True, help_text='The body text of the article.')),
                ('author', models.CharField(help_text='The name of the author who published the article.', max_length=30)),
                ('create_date', models.DateField(help_text='The date of the article.')),
            ],
        ),
    ]
